# site name
prefixName: 心から愛する
siteName: kcalm
# favicon and site master avatar
favicon: /images/boy.ico
avatar: /headPic/boy.jpg
url: https://www.lifepart.top/
description: 一面技术，一面生活
cdn: https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic
# cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 0
# 1开启
mathjax: 0

notice: 亲爱的，欢迎你的到来       
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    # 技术: {path: /categories/技术/, fa: fa-code }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o },
    # 转载: {path: /categories/转载/, fa: fa-book }
  } }
  # 清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
  #   书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
  #   番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
  #   歌单: {path: /music/, fa: fa-headphones },
  #   图集: {path: /tags/图集/, fa: fa-photo }
  # } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg1.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg2.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg5.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg6.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg7.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg8.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg9.jpg
  - https://cdn.jsdelivr.net/gh/kcalm-boy/ImgHosting/kcalm-Pic/BgPic/bg10.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 18/9/2020

#social  url, img PC端配置
social:
  # github: {url: http://github.com/kcalm0, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: /#, img: /social/wangyiyun.png}
  # zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: /#, img: /social/email.svg}
  QQ : {url: /#, qrcode: /social_account/QQ.png, img: /social/qq.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

# donate:
#   paypal: https://www.paypal.me/hojuncn
#   alipay: /img/custom/donate/AliPayQR.jpg
#   wechat: /img/custom/donate/WeChanQR.jpg
#   wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  enable: false  #这里是不允许放视频，可修改
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4


aplayer:  ##媒体播放引擎，移动端会禁止自动播放
  enable: false
  id: 5250803632
  server: netease
  type: playlist
  fixed: true ##开启吸底模式，固定到底部
  autoplay: true ##音频自动播放
  loop: all  ##音频循环播放, 可选值: 'all', 'one', 'none'
  order: random ##音频循环顺序, 可选值: 'list', 'random'
  preload: auto ##预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 ##默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  mutex: true ##互斥，阻止多个播放器同时播放


# Valine
valine: true
v_appId: aksMJEuA5ESaNc0jmGqk6keU-gzGzoHsz
v_appKey: yBJamB2baMNg543Brt8Qd9vu
